# Generated by Django 5.0 on 2025-10-01 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviepetition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepetition',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_petitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
