# Generated by Django 5.0 on 2025-10-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_moviepetition_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviepetition',
            old_name='votes',
            new_name='voters',
        ),
    ]
