# Generated by Django 5.0 on 2025-10-02 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_votes_moviepetition_voters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviepetition',
            old_name='voters',
            new_name='votes',
        ),
    ]
